version: "3"
services:
  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: postgres-db
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "max_connections=1000"]
